### ISSUE TITLE
Convert line endings from Windows to Ubuntu

### ISSUE THREAD

**Issue by techvoltage** [mmiszczyk/deepmage#3]
Ubuntu requires Unix-style line endings (LF). On Ubuntu 16.04, it throws error:
/usr/bin/env: ‘python3\r’: No such file or directory

**Comment by mmiszczyk** [comment]
that's weird, I just pulled the repo on Ubuntu and it works fine

**Comment by mmiszczyk** [comment]
Ok, I found out that the line endings were converted when pushing to git repo but not in the wheel. Fixing that right now.
